### Agregar un nuevo producto
POST http://localhost:5099/api/productos
Content-Type: application/json

{
  "categoriaId": 2,
  "nombre": "Panel Solar 100W",
  "descripcion": "Panel monocristalino de alta eficiencia.",
  "precio": 120.50,
  "stock": 50,
  "sku": "ECO-PANEL-100"
}